/**
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *     you may not use this file except in compliance with the License.
 *     You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 *     Unless required by applicable law or agreed to in writing, software
 *     distributed under the License is distributed on an "AS IS" BASIS,
 *     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *     See the License for the specific language governing permissions and
 *     limitations under the License.
 */
package org.foo;

import org.foo.data.MyEntityBean_;
import org.foo.data.jooq.tables.MyEntity;
import org.jooq.DSLContext;
import org.jooq.SQLDialect;
import org.jooq.impl.DSL;

public class Sample {

  public static void main(String[] args) {

    // JPA model (it gets generated by IntelliJ)
    MyEntityBean_.ID.toString();

    // jOOQ DSL (it does not get generated by IntelliJ)
    DSLContext ctx = DSL.using(SQLDialect.MYSQL);
    System.out.println(ctx.select().from(MyEntity.MY_ENTITY).getSQL());
  }
}
